### ISSUE TITLE
Low loud speaker volume

### ISSUE THREAD

**Issue by Poky14** [TheWhisp/android_device_samsung_wilcoxltexx#10]
A have issues in call, when i switch to loud speaker, volume is up, icon is in statusbar, but sound from the loud speaker is very low. This issues is on Android 4.4.4, build cm-11-20140629 and cm-11-20140626

**Comment by Poky14** [comment]
On the new release,cm-11-20140704 the same problem

**Comment by TheWhisp** [comment]
What do you mean by "very low" ? Seems fine to me.

**Comment by Poky14** [comment]
The volume is same as the front speaker, when a calling. I switch to loud speaker and i musst have put the phone back side to the ear, I'd even heard.  
This is only problem, when i call. In other times back speaker is ok.

I try it only update the ROM without any wipe and i try it clean install the ROM and same problem.
Sorry for my bad English

**Comment by TheWhisp** [comment]
Sorry, but I certainly do not experience such issue, I mean, I don't have to put it  by my ear to hear something. The volume is set to max, if I set it even 5-7 percent higher, it gets corrupted.

**Comment by Poky14** [comment]
I found a solution. I copy file from your first build - audio.primary.msm8960.so to system/lib/hw and now loud speaker in calling is volume in normal.

**Comment by TheWhisp** [comment]
It breaks mic

**Comment by Poky14** [comment]
This file from first release break mic, but loud handsfree in call is ok. On the latest release mic is ok, but loud handsfree is too low.

**Comment by shinra00** [comment]
i have to agree with Poky. On my device, with a clean install, the cm-11-20140629 build has the sound is very very low when on loud speaker.

**Comment by TheWhisp** [comment]
never mind, fixed

**Comment by shinra00** [comment]
really? nice! Thank you for the hardwork, can´t wait to try the new build :)
