### ISSUE TITLE
issues with voice calls

### ISSUE THREAD

**Issue by vdobunny** [TheWhisp/android_device_samsung_wilcoxltexx#11]
Hello, I have now the latest version ( 710 I belive) and I have some bug's with voice calls. Randomlly when I answer, I can't hear anything and nither does the person who call's me. The problem persists until the first reeboot or' power off made. I'm kind of new to this and I don't know how to find/create a log file that will further explain mai issue. In other new's it's a craking good ROM and I would gladly help you with any further info if you tell me how can I find it :d.

Congratulations on this fine work, respect!

**Comment by TheWhisp** [comment]
I have experienced the same problem. It seems to be occurring randomly. I have had this issue also on stock ROM  a few times, too. The next time you're in a situation like that, try toggling between speakerphone and earpiece and see what happens.

**Comment by vdobunny** [comment]
seems to be fine on latest update, having another issue :(
