### ISSUE TITLE
problem instaling apps

### ISSUE THREAD

**Issue by vdobunny** [TheWhisp/android_device_samsung_wilcoxltexx#12]
Hello, I seem to be having a new issue. I get the "insufficient memmory for instaling" message on some apps downloaded from the Play Store (eg. shazzam & others ). I have almost 800 Mb freespace on internal memorry :(. Tried to reinstal google apps, no use :(. Anybody had similar problems ??

**Comment by TheWhisp** [comment]
I cannot reproduce this issue.

**Comment by vdobunny** [comment]
Hello, did a fresh reinstall...and now it seems to be ok...I suspect it was an alternative market app that was at fault (Blackmart). Keep you posted.
