### ISSUE TITLE
Rotation screen

### ISSUE THREAD

**Issue by shinra00** [TheWhisp/android_device_samsung_wilcoxltexx#13]
Hey TheWhisp how are? Thank you for all the development.

So i found another minor bug but still wanted to report it. I have been using the app MobileVoip and even though the screen rotation is locked (the screen is not allowed to rotate) it will flip from vertical to horizontal whenever i´m using it.

Got a logcat here (with the screen rotation locked): https://www.dropbox.com/s/5xt2t0uobgekmp9/Logcat%20Rotation%20Screen.docx

Thank you for the time. Regards

**Comment by TheWhisp** [comment]
this is clearly not a device specific issue.

**Comment by shinra00** [comment]
i know this is closed but with stock rom MobileVoip would not rotate if the screen rotation lock was on.
