### ISSUE TITLE
MP3 problem

### ISSUE THREAD

**Issue by cezar57** [TheWhisp/android_device_samsung_wilcoxltexx#15]
Hello,
I have a problem playing the mp3 files in apollo. When i hit play it just goes on to the next track and so on. I found only 2 players that work : Poweramp and jetAudio
I also can't set any of this files as a ringtone.

**Comment by Riegusto** [comment]
Hello 
I'm having the same problem, no player does work at all. I tried apollo, google play music, musicmatch and so on...
Can we do something to fix it or do we have to wait for the next build?
Thx in advance.

**Comment by TheWhisp** [comment]
try disabling LPA, set lpa.decode to false in build.prop (as a workaround)
My music is stored in FLAC format on my device, that's why I didn't notice this problem.

**Comment by Riegusto** [comment]
Thx for the quick answer, everything is working great now. You did an amazing job with this ROM,  the stock ROM is really bad. Thanks to you the battery life of the phone more than 100% better :D thx again.
