### ISSUE TITLE
Bug app to sd and zoom camera

### ISSUE THREAD

**Issue by xxfabry89xx** [TheWhisp/android_device_samsung_wilcoxltexx#16]
It does not work the process to move the app to sd card . Zooming in the camera does not work ( I solved only by purchasing the app zoom camera fx) .

**Comment by kotzir** [comment]
App2SD was removed since android 4.3 Jelly Bean, so do not expect it to be...We also do not have zoom in camera(Galaxy Ace 3 LTE users)

**Comment by TheWhisp** [comment]
Just because Samsung has added some extra features in their ROMs doesn't mean it is a bug if a custom ROM doesn't include it.
