### ISSUE TITLE
Phone shuts down Randomly

### ISSUE THREAD

**Issue by Riegusto** [TheWhisp/android_device_samsung_wilcoxltexx#18]
Hello, 
The problem is as you can read that the phone powers off at random moments. Sometimes more than 4 times a day and sometimes it only does it ones in 3 days, so I really don't have a clue what the problem can be. I hope you can help me. Many thanks and it's a great ROM :D

**Comment by TheWhisp** [comment]
build version?

**Comment by Riegusto** [comment]
The latest version from 25/08.

**Comment by TheWhisp** [comment]
I'm not experiencing such issue
