### ISSUE TITLE
Wi-Fi Direct Share

### ISSUE THREAD

**Issue by megabitus98** [TheWhisp/android_device_samsung_wilcoxltexx#19]
Today Ive tried to send a file to my phone with Wi-Fi Direct, they found each other, and when the other phone started to send the file, on my phone nothing appeared.And after a while it said that it failed to send.Also I don't have the option to send with Wi-Fi Direct, only bluetooth appears.I have the latest rom: 11-20140918.

**Comment by kotzir** [comment]
This won't work like on stock rom, you need external apps (There are many on Play Store)
Sending files via Wifi-Direct without external application is made by Samsung and can't be used on CyanogenMod (proprietary implementation I suppose, correct me If I am wrong)

**Comment by TheWhisp** [comment]
The Wi-Fi is pretty much open source except for firmware. Anyhow, on the previous device I worked with (Mini 2 with ath6kl) there were also Wi-Fi Direct issues.

**Comment by megabitus98** [comment]
Thanks for helping, I've found a cool app SuperBeam, that works perfect.
