### ISSUE TITLE
Light sensor

### ISSUE THREAD

**Issue by shinra00** [TheWhisp/android_device_samsung_wilcoxltexx#22]
Hey, how are you?

I'm reporting that the light sensor isn't working. I used 2 apps to test the sensors and the light sensor doesn't even show up in the readings. The lightest app that i used to test was: Sensor Test from the playstore.

Thank you for the work.

**Comment by TheWhisp** [comment]
As far as I know Express 2 doesn't have a light sensor

**Comment by xxfabry89xx** [comment]
Although in the brightness bar appears " auto " is a bag, the sensor does not actually exist . Samsung had eliminated in the first update that came out for this smart phone .

**Comment by shinra00** [comment]
Thank you for the input. 

Thread Closed
