### ISSUE TITLE
Bug CM12

### ISSUE THREAD

**Issue by Dige90** [TheWhisp/android_device_samsung_wilcoxltexx#24]
bug I have personally encountered since I installed CM12. Battery overheating. Totally black screen after 2-3 hours of non-use (to restore it I need to remove the battery). It lacks the voice LTE -4G menu (in this version we know there is the tile as in CM11). I do not speak much of the NFC that is something already known. The phone will crash if you run a call by opening the Dialer app too quickly. Lacks the ability to insert options: RESTART - SCREENSHOTS - SILENT by the key off but remains just SHUT THE DEVICE. Upon installation of the CM12 touchscreen did not respond to my commands forcing me to turn off and use the data cable to rehabilitate the touch. There is a bug on the process of the clock. Every time you restart the phone, the clock back to 2 hours before. I think there is everything. Anyway, thanks for the work you have done. You May I install only your versions of CM and I have always enjoyed it. I can not write on XDA otherwise I would have done them. Sorry for my english ..
![screenshot_2014-11-25-01-53-42](https://cloud.githubusercontent.com/assets/9939700/5176229/eb1ab9f0-7445-11e4-8c61-91080a9cdd75.png)
![screenshot_2014-11-25-01-53-31](https://cloud.githubusercontent.com/assets/9939700/5176231/f26fd258-7445-11e4-9711-17c6e24cb90b.png)
![screenshot_2014-11-25-01-53-15](https://cloud.githubusercontent.com/assets/9939700/5176234/f7dbc0a8-7445-11e4-9723-5183175bc535.png)
![screenshot_2014-11-25-01-52-50](https://cloud.githubusercontent.com/assets/9939700/5176235/fdd986ca-7445-11e4-8a20-6af72127f7fd.png)

**Comment by Dige90** [comment]
![screenshot_2014-11-25-10-09-22](https://cloud.githubusercontent.com/assets/9939700/5190399/de76ea02-74e5-11e4-95ef-0718b6ad685b.png)

**Comment by TheWhisp** [comment]
First of all, that is just a preview build. It isn't meant to be used as a daily-driver. Second, most of the bugs you listed are about features that are not available in AOSP and are not yet implemented by CM. I only port the ROM, I don't add features to it.

**Comment by Leonardo141** [comment]
Hi, i'm live on Italy I would have to report a BUG on CyanogenMod 12 (Anyway great job) ;)
1) Some App close abnormally :(
2) The phone should support 4G
3) They should also be allowed to install SuperSu!
4) Very Battery Drain ..
5) Overheats often..
6) Make faster a phone.. 
Sorry for my English ..

**Comment by TheWhisp** [comment]
Did you read my previous post?
I have been using cm12 for about a week now:
1) Haven't experienced this
2) 4G (LTE) is working just fine
3) CM hasn't root support by default yet. Installing SuperSU manually works fine
4) Wi-Fi is draining battery a quite more than on CM11, otherwise battery performance is about the same as on CM11
5) Probably is caused by the same issue that is causing your battery drain
6) KitKat GPU and other blobs are still used

**Comment by LeonardoSpinale17** [comment]
When will be used then the GPU Lollipop ?
