### ISSUE TITLE
CyanogenMod 12 Samsung Galaxy Express 2 

### ISSUE THREAD

**Issue by Leonardo141** [TheWhisp/android_device_samsung_wilcoxltexx#25]
Hi TheWhisp, absolutely do not want to criticize the work. CyanogenMod 12 is very beautiful.. 
My purpose is to report bugs to make it even better the ROM.. I hope I was not too arrogant..
I LOVE CYANOGENMOD 12 <3

**Comment by Mariokoa** [comment]
New update for galaxy express 2?
