### ISSUE TITLE
Clock App on CyanogenMod 12

### ISSUE THREAD

**Issue by Leonardo141** [TheWhisp/android_device_samsung_wilcoxltexx#26]
Hi,The app "Clock " when you select the days of alarm repeat do not match Those selected ..
I'm have a Build LRX21Q CyanogenMod 12 Date 28/11/2014..
Below I leave two screen!

![screenshot_2014-12-03-20-27-04](https://cloud.githubusercontent.com/assets/9981082/5287961/1d980922-7b31-11e4-8e37-170fc9cf6236.png)

![screenshot_2014-12-03-20-27-11](https://cloud.githubusercontent.com/assets/9981082/5287963/236d5ae6-7b31-11e4-839e-5c93b2113c2f.png)

**Comment by TheWhisp** [comment]
Even if this is a bug, it's either in AOSP or CM. So report them at the appropriate place. This issue tracker is for device-specific bugs only

**Comment by Leonardo141** [comment]
But this problem will be fixed ?

**Comment by TheWhisp** [comment]
I don't know if this is even a bug, because I have set my alarm repeating on Tuesday and Friday and it looks just fine.

edit: Does the same thing happen if you select different language? Is your week set to start with Monday? From the screenshot it seems that the days are kind of "shifted" to the left.

**Comment by Leonardo141** [comment]
I do not know, i use the Italian language and Gives me this problem .. The days That I select are different from the ones I selected ..

**Comment by Leonardo141** [comment]
Example .. I selected : Sunday, Monday, Tuesday, Wednesday , Thursday, Friday ..
It says to me as if I had selelezionato : Monday , Tuesday, Wednesday , Thursday , Friday, Saturday!

**Comment by TheWhisp** [comment]
I don't know, it's fine for me

**Comment by Leonardo141** [comment]
I hope it will be resolved ...

**Comment by LeonardoSpinale17** [comment]
In Italy the week starts Monday and not Sunday ..
