### ISSUE TITLE
File Manager on CyanogenMod 12.. 

### ISSUE THREAD

**Issue by Leonardo141** [TheWhisp/android_device_samsung_wilcoxltexx#27]
Hi, what I see in the CyanogenMod 12 and does not have the file manager, then it is forced to download another app for managing files..

**Comment by TheWhisp** [comment]
Which part of "report only device specific-bugs here" did you exactly not understand? CM hadn't added it yet in that build, however, it is added now. Just wait for the new build

**Comment by LeonardoSpinale17** [comment]
Sorry, on new build the file manager is present ;)
