### ISSUE TITLE
CyanogenMod 12 Samsung Galaxy Express 2 

### ISSUE THREAD

**Issue by Leonardo141** [TheWhisp/android_device_samsung_wilcoxltexx#28]
When will a new build of CyanogeoMod12 ?

**Comment by Dige90** [comment]
Leonardo...qui si dovrebbe in teoria segnalare i bug, non chiedere info su nuovi build CM12

**Comment by LeonardoSpinale17** [comment]
Lo so Dige, ma ormai sono curioso di sapere quando usciranno le nuove build che correggeranno molti BUG che ha questo sistema.. chissà magari porterà anche la 5.0.1 =)
