### ISSUE TITLE
Recharging

### ISSUE THREAD

**Issue by alessio93** [TheWhisp/android_device_samsung_wilcoxltexx#3]
Hi,i nave a problemi with The recharging..when The telephone go at 0% battery i can't boot up while is on recharging,only if i go in CWM and select "reboot now" i can boot up,And when The telephone is active and under recharging The battery don't charge ( if is at 20% go to 19/18/17 etc... WHILE RECHARGE!)Please tell me how to fix it..thanks

**Comment by alessio93** [comment]
![sfd](https://cloud.githubusercontent.com/assets/7838732/3218103/9fc22d46-efe6-11e3-9316-26b9dfdb4baf.jpg)
White Samsung have CM11, Samsung blu stock rom, White don't charging, blu charging never problem, any idea?

**Comment by TheWhisp** [comment]
update to 07/06 build
