### ISSUE TITLE
[CM12]Clock Crash

### ISSUE THREAD

**Issue by megabitus98** [TheWhisp/android_device_samsung_wilcoxltexx#30]
Hi! I'm using the latest CM12 version and It has a nasty bug with the clock/alarm,every time when I try to create a new alarm the clock crashes(Logcat: http://pastebin.com/KtCjBe0y). Then when I start the clock again, the alarm icon appears in the notification bar then it starts to flash like crazy, and when I go to change the date/time/song the days checks and unchecks themselves, and also I can't change anything there.(Logcat: http://pastebin.com/zUkMtdtp)

**Comment by LeonardoSpinale17** [comment]
Strange, this does not happen in my phone ( CM12 ) you encountered this problem in the latest build ?

**Comment by megabitus98** [comment]
Yes, as I said before. I've done a clean reinstall and now It seems  fine, for now. I'll see what will happen in the future.

**Comment by LeonardoSpinale17** [comment]
Perfect, I hope she does not make any problem :)

**Comment by megabitus98** [comment]
For the last days I had no more problem, I guess that I installed something wrong. The problem is now fixed, so thanks.

**Comment by ruoso** [comment]
I just experienced the same problem after the Google asps got updated, that update also destroyed most of my user settings.

I am running the nightly from January 21. Will try updating to the latest (28) now to see what happens...

**Comment by TheWhisp** [comment]
This or any other similar problem hasn't occurred on my device since I first flashed L.

**Comment by Camtycai** [comment]
I have a similar issue on latest CM12 (Jan31). Once I trying to launch clock app, it will crash even before the number be seen. I have wiped everything before I install the CM12. I have no idea what's wrong on it.
