### ISSUE TITLE
Battery Drain on CyanogenMod 12 - WiFi Bug!

### ISSUE THREAD

**Issue by LeonardoSpinale17** [TheWhisp/android_device_samsung_wilcoxltexx#31]
Battery: For a while the battery of my Samsung Galaxy Express 2 is really bad .. I tried to buy it and calibrate it but nothing .. and the system as if consumed a lot of battery (Battery Drain ) can sometimes happen that I turn off the phone to 50 % and I find myself with a rate different from the previous .. This issue will be resolved please .. can no longer be so ! I have a CyanogenMod 12 with the latest build ; )
WiFi: Sometimes the WiFi when I turn off the phone by removing the battery , and start as if I had never Submitted passord of the WiFi ! ..
Sorry for my english!

![screenshot_2014-12-17-18-45-03](https://cloud.githubusercontent.com/assets/10134380/5475952/2b6a493c-861e-11e4-9cf9-ac6c291859c5.png)

![screenshot_2014-12-17-18-05-32](https://cloud.githubusercontent.com/assets/10134380/5475239/990e78de-8617-11e4-99bc-318d2a6825bd.png)

**Comment by LeonardoSpinale17** [comment]
I have installed a new build CyanogenMod 12.. (21/12/2014) But nothing , the bug are not resolved WiFi and Battery Drain , even if they add another 2 !
1 ) it is impossible to use Google Chrome or other browsers except stock
2 ) Google Play movie is locked abnormally always !

**Comment by LeonardoSpinale17** [comment]
![screenshot_2014-12-29-20-16-50](https://cloud.githubusercontent.com/assets/10134380/5571927/baf9dc84-8f97-11e4-84bd-1cc719317917.png)

**Comment by TheWhisp** [comment]
should be ok now

**Comment by LeonardoSpinale17** [comment]
Now Google Play Movies and Google Chrome are used 'm not having problems with the latest relase .. The battery seems to last more ..
