### ISSUE TITLE
Problem install apps

### ISSUE THREAD

**Issue by MarcoSanna2308** [TheWhisp/android_device_samsung_wilcoxltexx#33]
sometimes freezes, does not click the "install" on the app from unknown sources,only click the button "cancel". I've tried restarting, but nothing. Sorry for my english. I have cyanogenmod 12  21/12/2014.

**Comment by LeonardoSpinale17** [comment]
Hi, try to do a clean reinstall of the system ( Wipe Data / factory reset and Wipe Cache) and install the latest build; )
