### ISSUE TITLE
bug switching between 4G/3G

### ISSUE THREAD

**Issue by vdobunny** [TheWhisp/android_device_samsung_wilcoxltexx#37]
Hello, I have found that there is no option to come back to 4G mode if you switched to 3G. Any ideas ?

**Comment by TheWhisp** [comment]
this is probably a CM/AOSP general issue

**Comment by Poky14** [comment]
I use it https://play.google.com/store/apps/details?id=com.tapbase.LTEswitcher but i'm out of coverage LTE ;-) Try it ;-)
