### ISSUE TITLE
can't pick up the call

### ISSUE THREAD

**Issue by Poky14** [TheWhisp/android_device_samsung_wilcoxltexx#38]
On the latest build cm-12-20150321 I can't pick up the call when phone is ringing and home button in this screen don't work and i muss restart the phone. Whisp i hope for quick patch or update ;)

**Comment by vdobunny** [comment]
Hello there, I'm experiencing the same issue. Whent back to the previous version .

**Comment by TheWhisp** [comment]
This was discussed at xda thread and there is a fix for it.
