### ISSUE TITLE
Screen Mirroring / AllShare Cast Does't work

### ISSUE THREAD

**Issue by matgrand** [TheWhisp/android_device_samsung_wilcoxltexx#41]
First of all I'd like to say THANK YOU to you TheWhisp because you opened a new world to my express 2. The issue is about the fact that screen mirroring doesn't work on cm-12-20150221-UNOFFICIAL-wilcoxltexx.zip. The smartphone and the SmartTV (samsung) connect to each other but the mirroring doesn't start. Thank you in advance.

**Comment by TheWhisp** [comment]
I was once at my friends' house and noticed this issue. However I am unable to fix it since I do not have access to a SmartTV or any other device I could try Wi-Fi display on. AllShare is Samsung specific software and will not work on AOSP based ROMs.

**Comment by matgrand** [comment]
I see.. no problem... I just tried some apps and found one that solved the
problem perfectly.  Thank you for all. You are a great developer!!!!!
Il 24/Apr/2015 19:15, "Dāvis Mālnieks" notifications@github.com ha
scritto:

**Comment by matgrand** [comment]
Thank you very much!!!
Great job
