### ISSUE TITLE
[CM12] Unable to respond incoming calls

### ISSUE THREAD

**Issue by StrifeBaws** [TheWhisp/android_device_samsung_wilcoxltexx#42]
I can't respond incoming calls, I touch the button and swipe to the right to answer(or left to end it or up to send message), but nothing happens,the button just returns at the center of the screen.
![screenx](https://cloud.githubusercontent.com/assets/12096530/7315461/e8659326-ea6d-11e4-98bf-0c7bf0e085f1.PNG)

After the end of the call the screen remains the same, I have to remove the battery and restart the phone to get it running normal again.

**Comment by TheWhisp** [comment]
This was already discussed at XDA thread, it was a bug in one of the latest CM12 builds, however, it has been fixed. The details about this issue can be found in XDA thread
