### ISSUE TITLE
[CM12] Random system restarts

### ISSUE THREAD

**Issue by StrifeBaws** [TheWhisp/android_device_samsung_wilcoxltexx#43]
I turn on the phone and wait, everything normal until I arrive at ''Insert SIM PIN'' or the normal screen lock pin(I tried to disable them, nothing changes), I type the codes > after the codes i have 3 or 4 error messages : 

1- com.qualcomm.timeservice has stopped (not always, I'll explain below)
2- whatsapp has stopped
3- google play services stopped

Now, if I don't get the first error, the system keeps restarting over and over again(it just takes me back to the boot animation) and I have to remove the battery and wait a minute or two because I can't turn off the phone.
Also, my widgets aren't working at the start(all apps on internal memory), I have to remove and readd them to the screens

**Comment by TheWhisp** [comment]
I only restart my device after I flash a new build, sometimes the device up time is around 250 hours when I do so. Wipe data / factory reset your device. I don't experience any of those issues.
