### ISSUE TITLE
Wifi Fail to connect

### ISSUE THREAD

**Issue by sistro** [TheWhisp/android_device_samsung_wilcoxltexx#47]
Wifi ... sometimes stops working, it seems active, sees wifi networks but can not engage. Tried with various network and various router.

It is solved by restarting the phone.

**Comment by TheWhisp** [comment]
Works fine for me on 12.1... next time at least include the CM version and build date you're on.

**Comment by sistro** [comment]
I've forgotten to say that I'm using Cyanogenmod 12
cm-12-20150321-UNOFFICIAL-wilcoxltexx.zip

I say thanks for your works but If your don't have this issues doesn't mean that the problem doesn't exist!

I know that I'm a little bit OT here... but, when I install the rom all the device ram is formatted using Wipe data/factory reset or It's better that I format also something else? Maybe I've got this bugs becouse I've not upgraded rom in the right way.

**Comment by TheWhisp** [comment]
I cannot fix something I cannot reproduce. I use Wi-Fi at multiple places and have never had issues.
