### ISSUE TITLE
Screen freeze and restart!

### ISSUE THREAD

**Issue by PainKiller85** [TheWhisp/android_device_samsung_wilcoxltexx#48]
For no reason the device screen gets blocked(black screen) for no reason at all! I have noticed that sometimes it restarts itself suddenly! I do not know why, but this is the very first time when I experience this kind of troubles(not first time when I use Cyano or any other custom rom) and I would kindly ask you to fix them! Thanks!

**Comment by TheWhisp** [comment]
Doesn't seem to be happening anymore
