### ISSUE TITLE
Horizontal keyboard

### ISSUE THREAD

**Issue by shinra00** [TheWhisp/android_device_samsung_wilcoxltexx#5]
Hey, how are you?

So like most people i use Swiftkey as my keyboard because it is simply amazing. But i found out that if i have the device on horizontal the keyboard does not show, like if i am not writing anything.. If i rotate it to vertical it immediately shows up. Any idea?

thanks for the time

**Comment by TheWhisp** [comment]
I just testing it in couple of apps - cannot reproduce.
