### ISSUE TITLE
your device isn't compatible with this version

### ISSUE THREAD

**Issue by bilalazhar95** [TheWhisp/android_device_samsung_wilcoxltexx#50]
The latest 12.1 build have a problem in play store
Many apps like chrome and many basic other apps don't show up in the store.opening by external links in play store says 
"Your device isn't compatible with this version"

**Comment by nemanjas98** [comment]
Same for me. I installed the newest build, I saw this issue, and when i come back to previous build, issue is still there :(

**Comment by TheWhisp** [comment]
Should be fixed in the next build.

**Comment by bilalazhar95** [comment]
its fixed thanks :D
