### ISSUE TITLE
Skype

### ISSUE THREAD

**Issue by shinra00** [TheWhisp/android_device_samsung_wilcoxltexx#8]
Good morning how are you?

I would like to report an issue that i´ve noticed that on the previous version, cm-11-20140607-UNOFFICIAL-wilcoxltexx.zip it already existed.

Whenever i´m using skype if i place the phone on speaker the microphone gets disabled, the other person can´t hear any thing. If the call goes back to the normal standard the microphone works again.

Thank you for the help

**Comment by TheWhisp** [comment]
don't report bugs on older builds... No logs either. What do you expect me to do?

**Comment by shinra00** [comment]
This "problem" still exists in this build TheWhisp. Regarding the logs... i am pretty new to this android thing. I am trying to help with my experience but i don´t know how to save the logs or where to get them from. If you are kind enough to tell me, ill do my best to keep experimenting the builds and reporting any bugs i find, attached with logs.

Thank you

**Comment by TheWhisp** [comment]
In my opinion, "adb logcat" is not rocket science

**Comment by TheWhisp** [comment]
Can you reproduce if this happens in normal phone calls or just in VoIP?

**Comment by shinra00** [comment]
I've noticed that unfortunately this is also happening when on normal phone. If i go to speaker i can hear the person perfectly but i cannot be heard. The mic goes off. 

I'm trying to to recreate a log cat file but it is my very first time and i do not understand quite well how it works. Ill try to post as soon as possible.

thanks for the time

**Comment by shinra00** [comment]
Hey, so i installed Catlog and had it running for 3 min in total, did one test voice call where i turned on the speaker and the person could not hear me, turned it off, turned on and tuned it off. Then i went strait to catlog and stopped the recording. There are 150 pages of word :o !! and i do not understand a single thing.. i would like to reduce to what it matters but.. i have no clue what is what.

here is a the link for my dropbox account 

https://www.dropbox.com/s/n5pf3af8tfbi5or/Call%20-%20Catlog.docx

Thank you for the help TheWhisp

-----------edit.-------------

Does this help? or shall i do something diferent?

**Comment by shinra00** [comment]
Hey good morning how are you?

Thank you for the boot.img. So i used odin to boot it and unfortunately the
mic still goes off when on speaker. Doesn´t this happen on your device
also? Do you want me to retrieve a logcat?

Thank you for your time
-------edit---------
So i just noticed that after the boot via Odin of the boot.tar i cannot turn my wifi on. It says "Turning Wi-Fi on..." but nothing happens. It just stays there..

Going to create a logcat and submit it so that you can have some detailed information.

Thanks!

**Comment by TheWhisp** [comment]
Is it possible for you to take the same log on stock ROM? And while you're at it, pull /etc/snd_msm_soc/snd_msm_soc_2x

**Comment by shinra00** [comment]
sure, just give me one day please, my internet sucks and i have to download 950Mb (stockrom) and it says it will take 10hours.. O.o

**Comment by TheWhisp** [comment]
Seems that voice call speaker-mode MIC is now working for me. Could you confirm? Push this to /system/lib/hw/ and reboot: https://www.dropbox.com/s/ce34tcu9k1r9n78/audio.primary.msm8960.so
(note: Skype (VoIP) is still broken)

**Comment by TheWhisp** [comment]
fixed

**Comment by shinra00** [comment]
Nice thank you TheWhisp!
