### ISSUE TITLE
new phone, can't install rom

### ISSUE THREAD

**Issue by rhade87** [TheWhisp/android_device_samsung_wilcoxltexx#9]
I root-ed the phone, put the rom and the ClockWorkMod 6.0.4.8 on the sd card and tried a few times to install it.
When i boot into recovery mode, I only have
reboot system now
apply update from ADB
apply update from external storage
wipe data/factory reset
wipe cache partition
apply update from cache

I wipe data/factory reset but there is no /format system to do as required in "how to install" steps
When I try to install from external storage, I get an error, failed to verify whole-file signature but it says install complete and the phone restarts. But when it restarts, the stock rom is installing apps.
Please help.

**Comment by TheWhisp** [comment]
How is this related to the ROM? You clearly haven't flashed CWM, isn't that obvious?
